import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormField, Loader } from '../components'

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if(form.prompt && form.photo)
    {
      setLoading(true);
    
    try {
      const response =await fetch('https://ai-image-generation-7cye.onrender.com/api/v1/post',{
        method:'POST',
        headers:{
          'Content-Type':'application/json',
        },
        body:JSON.stringify(form)
      })
      await response.json();
      navigate('/'); 
    } catch (error) {
      alert(error)
      
    }
    finally{
      setLoading(false);
    }
   } else{
    alert('Please enter a prompt and generate an image');
   }
  }
  
  const handleChange = (e) => { 
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  const handleSurpriseMe = () => { 
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({ ...form, prompt: randomPrompt });
  }

  // ✔ FIXED FUNCTION FOR BYTEZ DALL-E (URL, not base64)
  const generateImage = async () => {
    if (!form.prompt) {
      alert("Please enter a prompt");
      return;
    }

    try {
      setGeneratingImg(true);

      const response = await fetch("https://ai-image-generation-7cye.onrender.com/api/v1/dalle/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt: form.prompt }),
      });

      const data = await response.json();
      console.log("IMAGE URL FROM BACKEND:", data.photo);

      if (!data.photo) {
        alert("No image returned. Try again.");
        return;
      }

      // ✔ Store direct URL, NO base64 prefix
      setForm({ ...form, photo: data.photo });

    } catch (error) {
      console.error("Generate image error:", error);
      alert("Error generating image: " + error.message);
    } finally {
      setGeneratingImg(false);
    }
  };

  return (
    <section className="max-w-7xl mx-auto px-4 flex justify-center">
      <div className="w-full max-w-3xl">
        
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">Create</h1>
          <p className="mt-2 text-[#666e75] text-[16px]">
            Create imaginative images generated by AI and share them with the community.
          </p>
        </div>

        <form className="mt-16 w-full" onSubmit={handleSubmit}>
          <div className="flex flex-col gap-5">

            <FormField
              LabelName="Your name"
              type="text"
              name="name"
              placeholder="Lara"
              value={form.name}
              handleChange={handleChange}
            />

            <FormField
              LabelName="Prompt"
              type="text"
              name="prompt"
              placeholder="A plush toy robot sitting against a yellow wall"
              value={form.prompt}
              handleChange={handleChange}
              isSurpriseMe
              handleSurpriseMe={handleSurpriseMe}
            />

            {/* IMAGE PREVIEW AREA */}
            <div className="relative bg-gray-50 border border-gray-300 text-gray-900 
                            rounded-lg w-64 h-64 p-3 flex justify-center items-center">

              {form.photo ? (
                <img
                  src={form.photo}  // ✔ DISPLAY DIRECT URL
                  alt={form.prompt}
                  className="w-full h-full object-contain"
                />
              ) : (
                <img
                  src={preview}
                  alt="preview"
                  className="w-9/12 h-9/12 object-contain opacity-40"
                />
              )}

              {generatingImg && (
                <div className="absolute inset-0 z-10 flex justify-center items-center 
                                bg-[rgba(0,0,0,0.5)] rounded-lg">
                  <Loader />
                </div>
              )}
            </div>

          </div>

          {/* BUTTONS */}
          <div className="mt-5 flex flex-col sm:flex-row gap-5 w-full">
            <button
              type="button"
              onClick={generateImage}
              className="text-white bg-green-700 font-medium rounded-md text-sm 
                         w-full sm:w-auto px-5 py-2.5 text-center"
            >
              {generatingImg ? 'Generating...' : 'Generate'}
            </button>
          </div>

          <div className="mt-10">
            <p className="mt-2 text-[#666e75] text-[14px]">
              Once your image is ready, you can share it with others.
            </p>

            <button
              type="submit"
              className="mt-3 text-white bg-[#6469ff] font-medium rounded-md 
                         text-sm w-full sm:w-auto px-5 py-2.5 text-center"
            >
              {loading ? 'Sharing...' : 'Share with the community'}
            </button>
          </div>

        </form>
      </div>
    </section>
  )
}

export default CreatePost
